<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('hr_employees', function (Blueprint $table): void {
            $table->id();
            $table->string('code', 40)->unique(); // EMP-0001, generated by EmployeeService
            $table->string('name');
            $table->string('nik_ktp', 16)->unique(); // 16-digit KTP number (also NIK-as-NPWP)
            $table->string('npwp', 30)->nullable();
            $table->string('gender', 10); // male | female
            $table->date('birth_date');
            $table->string('ptkp_status', 10); // TK/0 .. K/3
            $table->date('join_date');
            $table->string('employment_type', 20); // tetap | kontrak | harian
            $table->string('position', 100);
            $table->string('department', 30); // proyek | engineering | keuangan | hrga | procurement | servis
            $table->decimal('base_salary', 18, 2)->default(0);
            $table->json('fixed_allowances')->nullable(); // {"transport": 500000, "makan": 660000}
            $table->string('bpjs_kesehatan_no', 30)->nullable();
            $table->string('bpjs_tk_no', 30)->nullable();
            $table->string('bank_name', 60)->nullable();
            $table->string('bank_account_no', 40)->nullable();
            $table->string('bank_account_name', 100)->nullable();
            $table->string('status', 20)->default('active'); // active | resigned
            $table->date('resign_date')->nullable();
            $table->timestamps();
            $table->softDeletes();

            $table->index('status');
            $table->index('department');
        });

        // NOTE: the users.employee_id link is owned by the Iam module — no user_id column here.
    }

    public function down(): void
    {
        Schema::dropIfExists('hr_employees');
    }
};
